### ISSUE TITLE
goto/goToStep does not work if there are multiple sections in one document

### ISSUE THREAD

**Issue by Don42** [artomweb/Quick-Sip-Typst-Template#1]
First of, thank you for this template, I'm currently writing a collection of checklists for daily tasks.
For that I have six pages (scaled to 1/3 A4 but that shouldn't matter) each with one checklist (`#section`).
On page for I needed to add a `choose-one`/`chooseOne` item with `goto`/`goToStep` items in each branch.
Typst reports compiler errors for both:
> label `<step2>` occurs multiple times in the document
> label `<step9>` occurs multiple times in the document

I'm assuming the issue is, that the labels do not include a reference to the section they are contained in.

I've found some differences between the code here and the code in the typst packages repostiory. I hope leaving the issue here is correct.

**Comment by artomweb** [comment]
Hopefully fixed with 199da067f87383e0359dcce55711d6f9c084be43, I will update the package on Typst Universe (it takes a while to update), but the changes are available on this repo if you use Typst locally. Thanks for the feedback! This repo is now up to date with the Typst package so contributions here are welcome.

**Comment by Don42** [comment]
Thanks. Now it works.
